# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: rappdw/docker-java-python

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv*,.git,__pycache__,venv,roman_venv --statistics
            pytest -v


      # Step 4: run BD Detect
      - run:
          name: run detect
          command: |
            - bash <(curl -s -L https://detect.synopsys.com/detect.sh) --blackduck.url="https://poc39.blackduck.synopsys.com" \
            --blackduck.api.token="YjNkY2M5MTEtYWMzYS00ODZiLThhYzAtNDM5ODNmY2IxOTNjOjZjYzM1ZmUxLTI1MDQtNGZiMC04MzY0LTgzNTg4MDcxNGMwNw==" \
            --blackduck.trust.cert=true \
            --logging.level.detect=DEBUG \
            --detect.cleanup=false \
            --detect.project.name=alex_gitlab_ci_tests_3 \
            --detect.project.version.name=6.0
              